### ISSUE TITLE
coreLibraryDesugaringEnabled option in android/app/build.gradle causes immediate app crash with JNIReference Error

### ISSUE THREAD

**Issue by thejaimin** [google-home/sample-apps-for-matter-android#151]
if I add this setting in app gradle then getting crash at runtime

`
 compileOptions {
        coreLibraryDesugaringEnabled true
}
`

`
dependencies {
    coreLibraryDesugaring  'com.android.tools:desugar_jdk_libs:2.0.3'
}
`

Caused by: chip.devicecontroller.ChipDeviceControllerException: ../../src/lib/support/JniReferences.cpp:124: Error 0x00000702
        at chip.devicecontroller.ChipDeviceController.newDeviceController(Native Method)
        at chip.devicecontroller.ChipDeviceController.<init>(ChipDeviceController.java:58)

**Comment by pierredelisle** [comment]
Never saw this, but this seems to originate from the "arlo" app? You should probably inquire with that team.

**Comment by thejaimin** [comment]
This gradle options is affecting 
`
compileOptions { coreLibraryDesugaringEnabled true }
`
and this dependency 
`dependencies { coreLibraryDesugaring  'com.android.tools:desugar_jdk_libs:2.0.3' }
`

**Comment by pierredelisle** [comment]
Sorry, there is not context on why we would need this in the context of the sample app. Short of that, closing the issue.
