### ISSUE TITLE
Problem with the commissioning in the Google Eco-System

### ISSUE THREAD

**Issue by devRadorg** [google-home/sample-apps-for-matter-android#152]
Hello All,
I have a problem with the commissioning process in the Google Home Mobile SDK for Android. I want to commission our device with our Custom App in the Google Eco-System. So that I can see and use the device in our App and in the Google Home App. But I never see our device in the Google Home App.
I tried two ways:
I used the default CommissioningService of the Home Mobile SDK. The device commissioning was succeed and I can control it with our Custom App but not in the GHA.
I overwritten the CommissioningService like the Google Home Sample App for Matter. The device commissioning was succeed and I can control it with our Custom App but not in the GHA.
I think, I have a understanding misstake about the commissioning implementation of the Google Home Mobile SDK.
 Can someone explain what I do wrong?

**Comment by pierredelisle** [comment]
Note that the commissioning API commissions first to the local Android fabric, and then to the app's own fabric. It does not commission to the Google ecosystem fabric. Note that there are future plans for APIs that leverage the fact that some devices are on the local Android fabric.

**Comment by devRadorg** [comment]
Thanks for the explanation. Is there a way to add devices to the Google Ecosystem Fabric via our own app? We want that the Google Home App is the base App and our app is only for manufacturer specific functions.

**Comment by pierredelisle** [comment]
You may want to check https://developers.home.google.com/io#upcoming-preview-programs.

**Comment by devRadorg** [comment]
@pierredelisle Hello,
Two times I tried to register for this program but I got always nothing response. I heard that Google is going to fix this. Is there a date when it is released?
