### ISSUE TITLE
getDiscoveredDevice returns null with third_party/connectedhopmeip .jar and .so files

### ISSUE THREAD

**Issue by mukesh-simform** [google-home/sample-apps-for-matter-android#155]
I'm using these required by [CHIPTool .jar and .so files](https://github.com/google-home/sample-apps-for-matter-android/tree/main/3p-ecosystem/third_party/connectedhomeip/libs) directly in one of the apps and found that getDiscoveredDevice returns null every time despite discovering a service. Rest are working as expected including commissioning, clusters, etc.

<img width="947" alt="Screenshot 2023-07-31 at 11 49 24 AM" src="https://github.com/google-home/sample-apps-for-matter-android/assets/56827526/b6b449ac-1864-4b5b-8036-930ba66faeca">

Even the command-line shows discovered nodes with the following command `./chip-tool discover commissionables`

<img width="574" alt="Screenshot 2023-07-31 at 12 11 07 PM" src="https://github.com/google-home/sample-apps-for-matter-android/assets/56827526/bd4e4c37-a280-4d4e-bd48-4ea6ad1faf95">

And The same functioning is working fine in the [ChipTool sample app ](https://github.com/project-chip/connectedhomeip/tree/master/examples/android/CHIPTool) provided in the matter repository 

<img width="1058" alt="Screenshot 2023-07-27 at 4 35 57 PM" src="https://github.com/google-home/sample-apps-for-matter-android/assets/56827526/996b0afb-a780-42d7-bfcd-15b45cc15226">

Why this sample app still requires this [third_party/connectedhopmeip](https://github.com/google-home/sample-apps-for-matter-android/tree/main/3p-ecosystem/third_party/connectedhomeip) as a third-party dependency? Is it because all possible matter  SDK methods are not yet part of Google Home SDK matter API?

Also, How can these .jar or .so files will get updated? How can I regenerate these considering may be an issue with the .jar and .so files?

Here's my implementation 

<img width="762" alt="Screenshot 2023-07-28 at 4 41 13 PM" src="https://github.com/google-home/sample-apps-for-matter-android/assets/56827526/2cc3b689-9f50-44be-b310-3ed7680d02e0">

**Comment by pierredelisle** [comment]
The sample app uses some APIs provided by the Matter SDK (from https://github.com/project-chip/connectedhomeip).
These APIs are not exposed via the Google Home Mobile SDK, so that's why the .jar's and .so's are included in our project (note that this will soon be available as a Maven dependency).

If you build the Java ChipTool (from from https://github.com/project-chip/connectedhomeip), you should then build at the same time the .jar's and .so's needed for Android.

**Comment by mukesh-simform** [comment]
@pierredelisle  Make sense, That means Google Home Mobile SDK provides commissioning and device sharing only through Google Play Services and for other controls like accessing clusters, and all other available matter APIs we'll have to use these .jar and .so files until these will be available as a Maven dependency. 

Should we expect all other Mattter APIs in Google Home Mobile SDK ?
e.g pairWithAddress, pairDeviceWithCode, Clusters etc. 
https://github.com/project-chip/connectedhomeip/blob/fc595053e66bd120c6b74d77630a408ea0740f7f/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L35
