### ISSUE TITLE
awaitCommissionDevice, errorCode 773

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-apps-for-matter-android#157]
I keep landing here:
https://github.com/google-home/sample-apps-for-matter-android/blob/main/3p-ecosystem/src/main/java/com/google/homesampleapp/chip/ChipClient.kt#L181

With errorCode 773. What does errorCode 773 mean? and it is fatal? My device appears to be commissioned even though I am getting this error 773.  

I can't find any obvious reference to error 773 (0x305) in the CHIP code. The logs say errorCode [773] encountered, but there is no useful indication as to what caused it.

**Comment by pierredelisle** [comment]
I believe it would be this error code:
(from https://github.com/project-chip/connectedhomeip/blob/master/docs/ERROR_CODES.md#asn1-layer-errors)

> 773 | 0x305 | ASN1_ERROR_INVALID_ENCODING

Which would be triggered in chip.devicecontroller.ChipDeviceController:commissionDevice().

Full logs would be helpful. Also, developers at the CSA would be the ones to help shed some light on this.

**Comment by jonsmirl** [comment]
[773.log](https://github.com/google-home/sample-apps-for-matter-android/files/12325128/773.log)

Line 573.

**Comment by jonsmirl** [comment]
I have three identical Nanoleaf light bulbs. Two commissioned without error. Third is stuck on this.

**Comment by pierredelisle** [comment]
Sorry, can't really help here. Someone that can dig and understand chips's ChipDeviceController would be needed. Again, looks like developers at the CSA would be the ones to help shed some light on this.

**Comment by jonsmirl** [comment]
This turned out to be a Java issue with not having an unsigned data type. When my certificates passed through some Java code the certificate numbers which were Kotlin unsigned longs got turned into Java signed longs. If you go read the x509 spec it says certificate numbers can be 20 digits, but they can't be negative.  So the cert numbers were ok in Kotlin but not in Java. I have since adjusted my code to keep the cert number in the valid range for Java.
