### ISSUE TITLE
Encountered 12 files that should have been pointers, but weren't

### ISSUE THREAD

**Issue by OlivierGre** [google-home/sample-apps-for-matter-android#163]
I'm installing the latest version as explained on https://github.com/google-home/sample-apps-for-matter-android/tree/main/3p-ecosystem.

During the cloning operation, I'm seeing the following warnings:
```

$ git clone https://github.com/google-home/sample-apps-for-matter-android.git
Cloning into 'sample-apps-for-matter-android'...
remote: Enumerating objects: 1619, done.
remote: Counting objects: 100% (511/511), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 1619 (delta 351), reused 367 (delta 266), pack-reused 1108
Receiving objects: 100% (1619/1619), 30.34 MiB | 6.50 MiB/s, done.
Resolving deltas: 100% (727/727), done.
Updating files: 100% (214/214), done.
Encountered 12 files that should have been pointers, but weren't:
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/arm64-v8a/libCHIPController.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/arm64-v8a/libSetupPayloadParser.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/arm64-v8a/libc++_shared.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/armeabi-v7a/libCHIPController.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/armeabi-v7a/libSetupPayloadParser.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/armeabi-v7a/libc++_shared.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/x86/libCHIPController.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/x86/libSetupPayloadParser.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/x86/libc++_shared.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/x86_64/libCHIPController.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/x86_64/libSetupPayloadParser.so
        3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/x86_64/libc++_shared.so
```
Shall I do something to fix them?
Thanks

**Comment by OlivierGre** [comment]
I had a version of GHSAM from beginning of july which was working. I have downloaded https://github.com/google-home/sample-apps-for-matter-android/tree/main/3p-ecosystem but for the moment I don't succeed to build it.

I'm getting errors with Java version:

Build file 'C:\GIT\sample-apps-for-matter-android\3p-ecosystem\build.gradle.kts' line: 13
```

An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Could not create an instance of type com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated.
      > Could not create an instance of type com.android.build.gradle.internal.dsl.LintImpl$AgpDecorated.
         > Could not generate a decorated class for type LintImpl$AgpDecorated.
            > com/android/tools/lint/model/LintModelSeverity has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

```

**Comment by OlivierGre** [comment]
I then had this error:
"The project is using an incompatible version (AGP 8.1.0) of the Android Gradle plugin. Latest supported version is AGP 7.4.1"
so I have decided to update Android Studio to the latest version (Android Studio Giraffe).

Unfortunately Android Studio is now displaying this error:
![image](https://github.com/google-home/sample-apps-for-matter-android/assets/34505085/3a82ff94-129f-4867-b2dc-b39c5fd860c8)

Is GHSAM working with the latest version of Android Studio?

**Comment by tunm1228** [comment]
> Despite this error, the build is successful and I'm able to use GHSAM.

_I have fixed it by installing JDK 17 corretto_ => Please tell me which section it is in

**Comment by pierredelisle** [comment]
This is what I have in Android Studio Giraffe:

<img width="981" alt="Screenshot 2023-09-14 at 7 50 08 PM" src="https://github.com/google-home/sample-apps-for-matter-android/assets/10608685/d4556e2c-ae1b-4608-9cf3-bbda2086c7cd">

**Comment by jonsmirl** [comment]
This error is because you haven't done 'git lfs init' in your git directory.

**Comment by pierredelisle** [comment]
Please note that with v2.0.0 that was just released, we get the libraries from Maven so there is no need for 'git lfs' anymore.
