### ISSUE TITLE
How to build CHIPTool libraries ?

### ISSUE THREAD

**Issue by OlivierGre** [google-home/sample-apps-for-matter-android#164]
I want to add some debug prints in CHIPTool libraries and then run GHSAM. 
On an Ubuntu machine, I have built [connectedhomeip ](https://github.com/project-chip/connectedhomeip) (v1.1-branch).

I have then used the command 
`llvm-strip examples/android/CHIPTool/app/libs/jniLibs/arm64-v8a/libCHIPController.so`
to reduce its size.

Finally I have taken the content of connectedhomeip/examples/android/CHIPTool/app/libs and I have put it in sample-apps-for-matter-android\3p-ecosystem\third_party\connectedhomeip\libs.

Unfortunately, when I rebuild it fails with this error:
`e: file:///C:/GIT/sample-apps-for-matter-android/3p-ecosystem/src/main/java/com/google/homesampleapp/chip/ChipClient.kt:321:11 Object is not abstract and does not implement abstract member public abstract fun onError(attributePath: ChipAttributePath?, eventPath: ChipEventPath?, e: Exception): Unit defined in chip.devicecontroller.ReportCallback`

@pierredelisle Would you have some instructions to explain how you are regenerating CHIPTool libraries from connectedhomeip repository?

Thank you
Regards

**Comment by OlivierGre** [comment]
I have tried the master branch of [connectedhomeip ](https://github.com/project-chip/connectedhomeip) but I'm getting the same error:

`e: file:///C:/GIT/sample-apps-for-matter-android/3p-ecosystem/src/main/java/com/google/homesampleapp/chip/ChipClient.kt:321:11 Object is not abstract and does not implement abstract member public abstract fun onError(attributePath: ChipAttributePath?, eventPath: ChipEventPath?, e: Exception): Unit defined in chip.devicecontroller.ReportCallback`

**Comment by OlivierGre** [comment]
Instead of replacing the whole content of sample-apps-for-matter-android\3p-ecosystem\third_party\connectedhomeip\libs\jniLibs\arm64-v8a, I have only replaced "libc++_shared.so" and "libCHIPController.so".  Now it works.

**Comment by pierredelisle** [comment]
Olivier, yeah, it's often an adventure when running a build under connectedhomeip.

Normally, we simply build the libraries as follows (in the connectedhomeip directory)
./scripts/build/build_examples.py \
  --target android-arm-chip-tool \
  --target android-arm64-chip-tool \
  --target android-x86-chip-tool \
  --target android-x64-chip-tool \
  build

Anyway, if you still have an issue, give that a ty. You should be able to replace all the libraries.

**Comment by OlivierGre** [comment]
Thank you Pierre.
