### ISSUE TITLE
Documentation Misalignment with Current Repository

### ISSUE THREAD

**Issue by matinzd** [google-home/sample-apps-for-matter-android#169]
Hello Maintainers,

I was recently going through the [Codelab Matter Sample App](https://developers.home.google.com/codelabs/matter-sample-app), and I found myself a bit tangled up. It seems that the content in the repository and the documentation on the website aren't quite in sync, which has been causing a bit of confusion as I try to follow along.

I completely understand that maintaining a project of this scale is no easy task, and I truly appreciate all the hard work you guys put in. I was wondering if it might be possible to give the documentation a little spruce up to match the current state of the repository? It would make the learning curve a lot smoother for folks like myself who are eager to dive in and learn.

Alternatively, if updating the documentation is a bit too hefty a task at the moment, maybe we could add a note on the website indicating that the materials might not align perfectly? This way, new users can brace themselves for some detective work ahead! 😉

Thank you so much for considering my suggestion. I'm really excited about this project and looking forward to seeing it evolve.

**Comment by pierredelisle** [comment]
Hi Matin,

Thanks for filing this issue and sincere apologies. Totally agree we should be more diligent in keeping the codelab in sync with the latest source code. 

Point well taken. We'll hopefully have the codelab updated within a couple weeks.

Thanks again.

**Comment by pierredelisle** [comment]
Looks like I was overly optimistic when I said two weeks :-(
Here is the plan: I really want to migrate the app to use JetPack compose. As part of that, I will also make sure that all docs are up-to-date. No promise on ETA, but will be spending some cycles on it.

**Comment by matinzd** [comment]
No worries Pierre!

**Comment by pierredelisle** [comment]
Good news! v2.0.0 has been released
- The app has been migrated to Jetpack Compose
- We're now getting the matter demo SDK from Maven (no need for LFS anymore, yay!)
- The codelab has been updated to work on v2.0.0

Please give it a try and let us know of any issue.
And sorry again for the long delay... it's been busy around here...

**Comment by matinzd** [comment]
No worries! Thanks for the hard work. Appreciate it 🙌
