### ISSUE TITLE
can existing google fabric reused by other ecosystem custom app like (apple ios matter custom app)

### ISSUE THREAD

**Issue by DGithubAccount** [google-home/sample-apps-for-matter-android#177]
suppose we have two devices first one is android device and we commissioned matter enabled light bulb in google fabric and now can use reuse same fabric to apple custom app ?

**Comment by pierredelisle** [comment]
Usually, ecosystems have their own fabric. If you want a device to be accessible via different ecosystems, then you'd want to use multi-admin. If you want more information about multi-admin, you may want to check this: https://developers.home.google.com/matter/primer/fabric#multi-admin.
