### ISSUE TITLE
Matter integration setup issue

### ISSUE THREAD

**Issue by itsvirendrapalsingh** [google-home/sample-apps-for-matter-android#181]
Hi All,

I am not able to add the matter device with the sample code.

Sharing the information below to debug it.

GHSAFM-3p-ecosystem version: 1.4.2

device used to test:
Name: One plus Nord 2 5G (Android version 13)
Firmware : This is the testing device which I want to connect hub lessly, I am able to connect this with hub with google home app

Google Play Services version:  com.google.android.gms.optional_home [234414042] [23.44.14 (100400-0)] [Download:00000397/dl-Home.optional_234414100400.apk] [download:/Home.optional/234414100400:Home.optional:234414100400]

Phone logs: attachment
[my_logs_1.txt](https://github.com/google-home/sample-apps-for-matter-android/files/13536127/my_logs_1.txt)

Kindly help to resolved above issue, I also try with some other mobile devices but getting the same issue.

**Comment by pierredelisle** [comment]
I see the following from the logs:

`12-02 16:32:51.817 18027 18027 E SetupDeviceViewModel: Commissioning failed with state Failed to discover commissionable device. [CONTEXT service_id=336 ]`

Not easy to investigate these issues without additional information from the environment.
However, we have developed a tool that would provide additional information that would be very useful to dig deeper.
See https://github.com/project-chip/connectedhomeip/tree/master/src/tools/interop/idt.
Please have a look and give it a try.

**Comment by pierredelisle** [comment]
No further comments on this issue. Closing for now.
