### ISSUE TITLE
What else do I need to do if I don't jump to “google matter add fragment” after calling commissionDevice in viewModel

### ISSUE THREAD

**Issue by JasonClark2** [google-home/sample-apps-for-matter-android#184]
In the demo, Google's services are started through viewmodel in the fragment. How to directly jump to Google's service in the activity to add matterhub?
What else do I need to do if I don't jump after calling commissionDevice

**Comment by pierredelisle** [comment]
Sorry, not sure I understand your question. Please be more specific with pointers to the code to make sure we understand the issue you are having. 
When in doubt, please phrase your questions in a fashion similar to how you would do it in stackoverflow.
https://stackoverflow.com/help/how-to-ask

**Comment by pierredelisle** [comment]
No further comments provided. Closing for now.
