### ISSUE TITLE
How to connect thread device without using any middle dependencies

### ISSUE THREAD

**Issue by Numeez** [google-home/sample-apps-for-matter-android#185]
I want to connect nanoleaf bulb which is a thread device to GHSAFM
But I can't connect unless I use  google nest as OTBR(Open Thread Border Router) and it is difficult to connect to google nest is there any procedure to connect nest easily 
Is there any way to connect thread devices directly to the app

**Comment by pierredelisle** [comment]
Please be more specific with your question. What do you mean by "it is difficult to connect to google nest"?

When in doubt, please phrase your questions in a fashion similar to how you would do it in stackoverflow.
https://stackoverflow.com/help/how-to-ask
