### ISSUE TITLE
The operation of the 32-bit device

### ISSUE THREAD

**Issue by MakeMeCookie** [google-home/sample-apps-for-matter-android#187]
I want to run the app on a 32-bit device, but the error 'com.google.android.gms.common.api.api.apiException 17api CommissionClient.api is not available on this device.'
Among the apps I'm going to use instead of commissioning client.api, Google Cloud iot is down. Which API is available instead?

![google app error](https://github.com/google-home/sample-apps-for-matter-android/assets/116155637/56ed6cd9-6fd9-4ae9-b05a-cf875fba08eb)

**Comment by pierredelisle** [comment]
Google Play Services must be installed on your phone. 
See https://github.com/google-home/sample-apps-for-matter-android/wiki/How-to-investigate-issues-with-GHSAFM%E2%80%903p%E2%80%90ecosystem

**Comment by pierredelisle** [comment]
Assuming all is good as we have not heard back. Closing for now.
