### ISSUE TITLE
Which API should be used to discover matter devices in network ?

### ISSUE THREAD

**Issue by KhushbuShah25** [google-home/sample-apps-for-matter-android#196]
Hi all,
Which API should be used to discover matter devices in network ? 
Is there any example or sample code for Matter device discovery for Android ?

Thanks.

**Comment by pierredelisle** [comment]
The sample app has a screen that shows all the commissionable Matter devices.
Try it as follows:
Settings (top right gear icon) > Developer utilities > Commissionable devices

You can see the code that makes that possible in the following package: https://github.com/google-home/sample-apps-for-matter-android/tree/main/3p-ecosystem/src/main/java/com/google/homesampleapp/screens/commissionable.
