### ISSUE TITLE
Jetpack Compose version 

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-apps-for-matter-android#25]
I am finding it difficult to translate some of the commissioning features of this app over to Jetpack Compose. It would be very helpful to have a Compose version of it.

**Comment by pierredelisle** [comment]
Would you have more specifics as to which "commissioning features" you are referring to?

**Comment by jonsmirl** [comment]
I am still trying to get it all sorted out with Compose
Like this 
```
    val commissionDeviceLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.StartIntentSenderForResult()
    ) { result ->
        // The Commission Device activity in GPS has completed.
        val resultCode = result.resultCode
        Timber.d("GOT result for commissioningLauncher: resultCode [${resultCode}]")
        if (resultCode == Activity.RESULT_OK) {
            viewModel.commissionDeviceSucceeded(
                result, context.getString(R.string.commission_device_status_success))
        } else {
            viewModel.commissionDeviceFailed(context.getString(R.string.status_failed_with, resultCode))
        }
    }
    commissionDeviceIntentSender.value?.let {
        commissionDeviceLauncher.launch(IntentSenderRequest.Builder(it).build())
    }
```
or this to remove the Observers...
```
    private val devicesUiModelFlow =
        combine(devicesFlow, devicesStateFlow, userPreferencesFlow) {
                devices: Devices,
                devicesStates: DevicesState,
                userPreferences: UserPreferences ->
            Timber.d("*** devicesUiModelFlow changed ***")
            return@combine DevicesUiModel(
                devices = processDevices(devices, devicesStates, userPreferences),
                showCodelabInfo = !userPreferences.hideCodelabInfo,
                showOfflineDevices = !userPreferences.hideOfflineDevices)
        }

    val deviceUIModel = devicesUiModelFlow.stateIn(viewModelScope, SharingStarted.WhileSubscribed(), DevicesUiModel(listOf<DeviceUiModel>(), false, false))
```

**Comment by pierredelisle** [comment]
Hey Jon, I'm not sure I follow. Jetpack Compose is the new toolkit for building native UI (https://developer.android.com/jetpack/compose). Where does it fit in the code snippets you showed?

**Comment by jonsmirl** [comment]
When you stop using Fragments, your code has to change quite a bit. Since this is a new app for us (and probably everyone else) we want to use the new toolkit.  Those snippets are code that has been restructured to work with Compose.

Take this simple Compose example (https://github.com/FirebaseExtended/make-it-so-android) and try to add CHIP to it.
You'll discover that you have to rewrite most of the GHSAFM code to make it work with Compose.

So my request would be to switch GHSAFM over to Compose, or develop a parallel app using Compose.

**Comment by pierredelisle** [comment]
Thanks for the clarification Jon, makes sense now.

When we first started coding the app we debated using Compose or not. In the end we decided against it to reduce the learning curve of android developers, as compose is still quite new, and a majority of devs would not have been exposed to compose just yet.

This being said, if Compose has reached critical mass and we don't have any strong pushback from whoever monitors this project, I'm all for migrating to Compose. 
However, we won't have resources on our side to work on this for some time. If you can provide a PR that does the migration, we'd be happy to review and merge. Thanks!

**Comment by jonsmirl** [comment]
For us this is a new app. We did not want to build a new app which is likely to be around ten years or more into the future on the old APIs. I am doing this conversion work in our new app, not the sample one, and since that code is very different from the sample a PR is unlikely.

Maybe the solution is to just have two sample apps?

**Comment by pierredelisle** [comment]
Migration to Jetpack Compose has been completed. See v2.0.0.
